# Service for coordinator instances internal
{{- range .Values.coordinators }}
---
apiVersion: v1
kind: Service
metadata:
  name: memgraph-coordinator-{{ .id }}
spec:
  type: ClusterIP
  selector:
    app: memgraph-coordinator-{{ .id }}
  ports:
    - protocol: TCP
      name: bolt
      port: {{ .boltPort }}
      targetPort: {{ .boltPort }}
    - protocol: TCP
      name: coordinator
      port: {{ .coordinatorPort }}
      targetPort: {{ .coordinatorPort }}
    - protocol: TCP
      name: management
      port: {{ .managementPort }}
      targetPort: {{ .managementPort }}
{{- end }}

# Service for coordinators instances external
{{- range .Values.coordinators }}
---
apiVersion: v1
kind: Service
metadata:
  name: memgraph-coordinator-{{ .id }}-external
spec:
  type: NodePort
  selector:
    app: memgraph-coordinator-{{ .id }}
  ports:
    - protocol: TCP
      name: bolt
      port: {{ .boltPort }}
      targetPort: {{ .boltPort }}
{{- end }}
